version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "7.4-apache-4"
    volumes:
      - ..:/workspace:cached
    # Uncomment the next line to use a non-root user for all processes.
    user: www-data
    ports:
      - "8080"
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  chromedriver:
    image: robcherry/docker-chromedriver:latest
    volumes:
      - /dev/shm:/dev/shm # See https://github.com/elgalu/docker-selenium/issues/20#issuecomment-325090454
    ports:
      - "4444"
    environment:
      CHROMEDRIVER_WHITELISTED_IPS: ""
      CHROMEDRIVER_URL_BASE: "/wd/hub"
    security_opt:
      - seccomp:unconfined
volumes:
  mariadb-data: null
